### ISSUE TITLE
Irreducible Force Constant Examples

### ISSUE THREAD

**Issue by ejmeitz** [spglib/spgrep#150]
I was wondering if there are any examples or if you are aware of anyone who has used spgrep to find the irreducible force constants for a given crystal? I saw the examples on lattice vibrations which are very similar, however, not quite what I was after. 

I am no expert in group theory, so best I understand it is that the block diagonalization of the dynamical matrix is somehow related to the irreducible form (maybe it is the irreducible form), but then my questions are:
- How does this extend to tensors (e.g. third order force constants)
- Where can I find resources combining the irreducible representation idea with lattice vibrations (phonons). Many of the group theory papers are too dense and most of the lattice vibration papers gloss over these steps. 

Thanks!

**Comment by lan496** [comment]
https://journals.aps.org/prb/abstract/10.1103/PhysRevB.100.014303
This article uses group representation theory to compute an anharmonic phonon. But, currently I am not clear how to implement such a method with spgrep.

https://journals.aps.org/rmp/abstract/10.1103/RevModPhys.40.1
For other resources for irreducible representation for phonon, I recommend this Maradudin's review.

**Comment by ejmeitz** [comment]
Thanks Ill check those out.
