### ISSUE TITLE
Identify a possible isomorphism between two space groups.

### ISSUE THREAD

**Issue by hongyi-zhao** [spglib/spgrep#24]
Based on the generators of space group 141 listed [here](https://www.cryst.ehu.es/cgi-bin/cryst/programs//nph-trgen?gnum=141&what=gen&trmat=a,b+1/4,c-1/8&unconv=I%2041/a%20m%20d%20:1&from=ita), the following GAP checking can be performed:

```gap
gap> gensSGITA141O1:=[
>  [[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 1, 0], [0,0,0,1]],
>  [[-1, 0, 0, 1/2], [0, -1, 0, 1/2], [0, 0, 1, 1/2], [0,0,0, 1]],
>  [[0, -1, 0, 0], [1, 0, 0, 1/2], [0, 0, 1, 1/4], [0,0,0, 1]],
>  [[-1, 0, 0, 1/2], [0,  1, 0,  0], [0,  0,  -1, 3/4], [0,0,0, 1]],
>  [[-1, 0, 0, 0], [0, -1, 0, 1/2], [0, 0, -1, 1/4], [0,0,0, 1]],
>  [[1, 0, 0, 1/2], [0, 1, 0, 1/2], [0, 0, 1, 1/2], [0,0,0, 1]]
> ];;
gap> gensSGITA141O2:=[
>  [[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 1, 0], [0,0,0, 1]],
>  [[-1, 0, 0, 1/2], [0, -1, 0, 0], [0, 0, 1, 1/2], [0,0,0, 1]],
>  [[0, -1, 0, 1/4], [1, 0, 0, 3/4], [0, 0, 1, 1/4], [0,0,0, 1]],
>  [[-1, 0, 0, 1/2], [0, 1, 0, 0], [0, 0, -1, 1/2], [0,0,0, 1]],
>  [[-1, 0, 0, 0], [0, -1, 0, 0], [0, 0, -1, 0], [0,0,0, 1]],
>  [[1, 0, 0, 1/2], [0, 1, 0, 1/2], [0, 0, 1, 1/2], [0,0,0, 1]]
> ];;
gap> SGITA141O1:=AffineCrystGroupOnLeft(gensSGITA141O1);
<matrix group with 6 generators>
gap> SGITA141O2:=AffineCrystGroupOnLeft(gensSGITA141O2);
<matrix group with 6 generators>
gap> ConjugatorSpaceGroups(SGITA141O1, SGITA141O2);
[ [ 1, 0, 0, 0 ], [ 0, 1, 0, 1/4 ], [ 0, 0, 1, 7/8 ], [ 0, 0, 0, 1 ] ]
```
Can the package perform the above or similar work to identify a possible isomorphism between two space groups?

Regards,
Zhao

**Comment by lan496** [comment]
I understand your question is how to identify transformation $(\mathbf{P}, \mathbf{p})$ for given two isomorphic space groups, $\mathcal{G}\_{1}$ and $\mathcal{G}\_{2}$, such that $(\mathbf{P}, \mathbf{p})^{-1} \mathcal{G}\_{1} (\mathbf{P}, \mathbf{p}) = \mathcal{G}\_{2}$. If so, spgrep does not provide a corresponding functionality.

**Comment by hongyi-zhao** [comment]
Your understanding of my question is completely correct. Thank you for your explanation and reply.

**Comment by hongyi-zhao** [comment]
The core foundation of the question discussed here is [Bieberbach's theorems](https://en.wikipedia.org/wiki/Space_group#In_other_dimensions) on which I have completed my own implementation in GAP, as shown below:

```gap
gap> S1:=SpaceGroupOnRightIT(3,227);
SpaceGroupOnRightIT(3,227,'2')
gap> S2:=SpaceGroupOnRightBBNWZ(3,227);
SpaceGroupOnRightBBNWZ( 3, 7, 5, 2, 4 )
gap> conj:=AffineIsomorphismSpaceGroups( S1, S2 );
[ [ 1/2, 1/2, 0, 0 ], [ 0, 1/2, 1/2, 0 ], [ 1/2, 0, 1/2, 0 ], [ 0, 0, 0, 1 ] ]
gap> S1^(conj^-1)=S2;
true
```
