### ISSUE TITLE
Some confusion on the description in the joss paper of this project.

### ISSUE THREAD

**Issue by hongyi-zhao** [spglib/spgrep#97]
In [the joss paper of this project](https://joss.theoj.org/papers/10.21105/joss.05269), I noticed the following description:

![image](https://github.com/spglib/spgrep/assets/11155854/06ac30f4-52fe-45d5-995b-d84120462af1)

1. You said **"Although these packages do not rely on tabulations of irreps"**

According to my understanding, the irvsp program also relies on table lookups. More specifically, it depends on the necessary information from the appropriate BCS database to execute its tasks, and its calculations are restricted to trace information exclusively.

2. You said **"spgrep provides unique irreps for given space groups"**

If the basis/wave function is specified first, then the representation matrix is completely determined; however, if the representation matrix is given first, the basis/wave function is naturally not unique.

So, I'm still unclear about what you're trying to express by saying "spgrep provides unique irreps for given space groups". It's unclear what you're referring to.

The representation matrix you provided naturally corresponds to a specific basis, and after changing the basis, it simply changes to an equivalent representation too.

3. What's **"a deterministic symmetry-adapted basis"** and why must it be unique?

Regards,
Zhao

**Comment by lan496** [comment]
Thank you for your comment on the tiny description. 

1. I agree this sentence is confusing. I mean irreps can be calculated by Bloch wave functions for each eigenenergy, and the construction of irreps itself does not rely on other tabulations.
2. Of course we can choose any vector spaces with the irreps's dimensions. Spgrep simply provides representation matrices calculated in a deterministic algorithm.
3. I mean symmetry-adapted basis constructed by the unique irreps. In total, we say the uniqueness of irreps up to representation matrices.

**Comment by hongyi-zhao** [comment]
If I understand correctly, your main point is as follows:

Your representation is not obtained from a table lookup but is directly calculated using a specific algorithm. Moreover, this algorithm also provides the corresponding basis, and that's all there is to it. In fact, for people doing physics, it doesn't matter how the representation is derived; what matters more is having the appropriate representation and knowing how to use it.

Am I right?

Regards,
Zhao

**Comment by lan496** [comment]
Yes, this package only concerns representation matrices.
